// Code generated by protoc-gen-go. DO NOT EDIT.
// source: personv35.proto

/*
Package person is a generated protocol buffer package.

It is generated from these files:
	personv35.proto

It has these top-level messages:
	Person
	PersonList
	Empty
*/
package person

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Person struct {
	Name  *Person_Name    `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Email []*Person_Email `protobuf:"bytes,2,rep,name=email" json:"email,omitempty"`
}

func (m *Person) Reset()                    { *m = Person{} }
func (m *Person) String() string            { return proto.CompactTextString(m) }
func (*Person) ProtoMessage()               {}
func (*Person) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Person) GetName() *Person_Name {
	if m != nil {
		return m.Name
	}
	return nil
}

func (m *Person) GetEmail() []*Person_Email {
	if m != nil {
		return m.Email
	}
	return nil
}

type Person_Name struct {
	Family   string `protobuf:"bytes,1,opt,name=family" json:"family,omitempty"`
	Personal string `protobuf:"bytes,2,opt,name=personal" json:"personal,omitempty"`
}

func (m *Person_Name) Reset()                    { *m = Person_Name{} }
func (m *Person_Name) String() string            { return proto.CompactTextString(m) }
func (*Person_Name) ProtoMessage()               {}
func (*Person_Name) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0, 0} }

func (m *Person_Name) GetFamily() string {
	if m != nil {
		return m.Family
	}
	return ""
}

func (m *Person_Name) GetPersonal() string {
	if m != nil {
		return m.Personal
	}
	return ""
}

type Person_Email struct {
	Kind    string `protobuf:"bytes,1,opt,name=kind" json:"kind,omitempty"`
	Address string `protobuf:"bytes,2,opt,name=address" json:"address,omitempty"`
}

func (m *Person_Email) Reset()                    { *m = Person_Email{} }
func (m *Person_Email) String() string            { return proto.CompactTextString(m) }
func (*Person_Email) ProtoMessage()               {}
func (*Person_Email) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0, 1} }

func (m *Person_Email) GetKind() string {
	if m != nil {
		return m.Kind
	}
	return ""
}

func (m *Person_Email) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

type PersonList struct {
	Persons []*Person `protobuf:"bytes,1,rep,name=persons" json:"persons,omitempty"`
}

func (m *PersonList) Reset()                    { *m = PersonList{} }
func (m *PersonList) String() string            { return proto.CompactTextString(m) }
func (*PersonList) ProtoMessage()               {}
func (*PersonList) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *PersonList) GetPersons() []*Person {
	if m != nil {
		return m.Persons
	}
	return nil
}

type Empty struct {
}

func (m *Empty) Reset()                    { *m = Empty{} }
func (m *Empty) String() string            { return proto.CompactTextString(m) }
func (*Empty) ProtoMessage()               {}
func (*Empty) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func init() {
	proto.RegisterType((*Person)(nil), "person.Person")
	proto.RegisterType((*Person_Name)(nil), "person.Person.Name")
	proto.RegisterType((*Person_Email)(nil), "person.Person.Email")
	proto.RegisterType((*PersonList)(nil), "person.PersonList")
	proto.RegisterType((*Empty)(nil), "person.Empty")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for PersonService service

type PersonServiceClient interface {
	Echo(ctx context.Context, in *Person, opts ...grpc.CallOption) (*Person, error)
	GetPersonStream(ctx context.Context, in *Empty, opts ...grpc.CallOption) (PersonService_GetPersonStreamClient, error)
}

type personServiceClient struct {
	cc *grpc.ClientConn
}

func NewPersonServiceClient(cc *grpc.ClientConn) PersonServiceClient {
	return &personServiceClient{cc}
}

func (c *personServiceClient) Echo(ctx context.Context, in *Person, opts ...grpc.CallOption) (*Person, error) {
	out := new(Person)
	err := grpc.Invoke(ctx, "/person.PersonService/Echo", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *personServiceClient) GetPersonStream(ctx context.Context, in *Empty, opts ...grpc.CallOption) (PersonService_GetPersonStreamClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_PersonService_serviceDesc.Streams[0], c.cc, "/person.PersonService/GetPersonStream", opts...)
	if err != nil {
		return nil, err
	}
	x := &personServiceGetPersonStreamClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type PersonService_GetPersonStreamClient interface {
	Recv() (*Person, error)
	grpc.ClientStream
}

type personServiceGetPersonStreamClient struct {
	grpc.ClientStream
}

func (x *personServiceGetPersonStreamClient) Recv() (*Person, error) {
	m := new(Person)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// Server API for PersonService service

type PersonServiceServer interface {
	Echo(context.Context, *Person) (*Person, error)
	GetPersonStream(*Empty, PersonService_GetPersonStreamServer) error
}

func RegisterPersonServiceServer(s *grpc.Server, srv PersonServiceServer) {
	s.RegisterService(&_PersonService_serviceDesc, srv)
}

func _PersonService_Echo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Person)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PersonServiceServer).Echo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/person.PersonService/Echo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PersonServiceServer).Echo(ctx, req.(*Person))
	}
	return interceptor(ctx, in, info, handler)
}

func _PersonService_GetPersonStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(Empty)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(PersonServiceServer).GetPersonStream(m, &personServiceGetPersonStreamServer{stream})
}

type PersonService_GetPersonStreamServer interface {
	Send(*Person) error
	grpc.ServerStream
}

type personServiceGetPersonStreamServer struct {
	grpc.ServerStream
}

func (x *personServiceGetPersonStreamServer) Send(m *Person) error {
	return x.ServerStream.SendMsg(m)
}

var _PersonService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "person.PersonService",
	HandlerType: (*PersonServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Echo",
			Handler:    _PersonService_Echo_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "GetPersonStream",
			Handler:       _PersonService_GetPersonStream_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "personv35.proto",
}

func init() { proto.RegisterFile("personv35.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 260 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x64, 0x91, 0x51, 0x4b, 0xc3, 0x30,
	0x14, 0x85, 0x8d, 0x76, 0xad, 0xde, 0x31, 0x07, 0x57, 0x91, 0xd2, 0xa7, 0xd1, 0x17, 0x8b, 0x0f,
	0x45, 0x3a, 0xe7, 0x83, 0xef, 0xc3, 0x17, 0x11, 0xa9, 0xbf, 0x20, 0xae, 0x57, 0x0c, 0x2e, 0x4d,
	0x49, 0xc2, 0xa0, 0xff, 0xd2, 0x9f, 0x24, 0x49, 0x5a, 0xc1, 0xee, 0xed, 0x9e, 0x9e, 0xf3, 0x9d,
	0x1e, 0x08, 0x2c, 0x3b, 0xd2, 0x46, 0xb5, 0x87, 0xf5, 0xa6, 0xec, 0xb4, 0xb2, 0x0a, 0xe3, 0xf0,
	0x21, 0xff, 0x61, 0x10, 0xbf, 0xf9, 0x13, 0x6f, 0x21, 0x6a, 0xb9, 0xa4, 0x94, 0xad, 0x58, 0x31,
	0xaf, 0xae, 0xca, 0x90, 0x28, 0x83, 0x5b, 0xbe, 0x72, 0x49, 0xb5, 0x0f, 0xe0, 0x1d, 0xcc, 0x48,
	0x72, 0xb1, 0x4f, 0x4f, 0x57, 0x67, 0xc5, 0xbc, 0xba, 0x9e, 0x24, 0xb7, 0xce, 0xab, 0x43, 0x24,
	0x7b, 0x82, 0xc8, 0x91, 0x78, 0x03, 0xf1, 0x27, 0x97, 0x62, 0xdf, 0xfb, 0xfa, 0x8b, 0x7a, 0x50,
	0x98, 0xc1, 0x79, 0xa0, 0xb9, 0xab, 0x73, 0xce, 0x9f, 0xce, 0x36, 0x30, 0xf3, 0x5d, 0x88, 0x10,
	0x7d, 0x8b, 0xb6, 0x19, 0x50, 0x7f, 0x63, 0x0a, 0x09, 0x6f, 0x1a, 0x4d, 0xc6, 0x0c, 0xdc, 0x28,
	0xf3, 0x47, 0x80, 0xb0, 0xe4, 0x45, 0x18, 0x8b, 0x05, 0x24, 0xa1, 0xd0, 0xa4, 0xcc, 0xcf, 0xbd,
	0xfc, 0x3f, 0xb7, 0x1e, 0xed, 0x3c, 0x71, 0xbf, 0xeb, 0x6c, 0x5f, 0x29, 0x58, 0x04, 0xef, 0x9d,
	0xf4, 0x41, 0xec, 0x08, 0x0b, 0x88, 0xb6, 0xbb, 0x2f, 0x85, 0x13, 0x34, 0x9b, 0xe8, 0xfc, 0x04,
	0x1f, 0x60, 0xf9, 0x4c, 0x76, 0xa0, 0xad, 0x26, 0x2e, 0x71, 0x31, 0x86, 0x7c, 0xf9, 0x31, 0x73,
	0xcf, 0x3e, 0x62, 0xff, 0x26, 0xeb, 0xdf, 0x00, 0x00, 0x00, 0xff, 0xff, 0x84, 0xc5, 0x21, 0x4f,
	0xa6, 0x01, 0x00, 0x00,
}
